name: blackseagypsy
favicon: null
layout_spectrum: 0.2977232
typography_spectrum: 0.542199
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b47d5e'
    - '#d6ab7f'
    - '#00200e'
    - '#556952'
    - '#fed0a3'
  brandStrength: 0.375
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
